org: fe24school
service: message-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - PUT
      allowedHeaders:
        - Content-Type

  iam:
    role: arn:aws:iam::575935530538:role/lecture-role

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  GetAllMessages:
    handler: functions/GetAllMessages/index.handler
    events:
      - httpApi:
          path: /messages
          method: GET
          cors: true
  
  CreateMessage:
    handler: functions/CreateMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: POST
          cors: true
  
  AddMessage:
    handler: functions/ChangeMessage/index.handler
    events:
      - httpApi:
          path: /messages
          method: PUT
          cors: true
  
  FilterUsers:
    handler: functions/FilterUsers/index.handler
    events:
      - httpApi:
          path: /messages/{username}
          method: GET
          cors: true
